apiVersion: v1
kind: Secret
metadata:
  name:  ${SECRET_NAME}
  namespace: ${NAMESPACE} 
  labels:
    app.kubernetes.io/part-of: gardener-extension-ontap
    app.kubernetes.io/managed-by: gardener
    ontap.metal-stack.io/project-id:  ${PROJECT_ID}
type: Opaque
stringData:
  username:  ${USER_NAME}
  password:  ${PASSWORD}