kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: basic
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ontap-gold
