apiVersion: v1
kind: Secret
metadata:
  name: ontap-svm-b5f26a3b9a4d48dba6b3d1dd4ac4abec-credentials
  namespace: kube-system
  labels:
    app.kubernetes.io/part-of: gardener-extension-ontap
    app.kubernetes.io/managed-by: gardener
    ontap.metal-stack.io/project-id: b5f26a3b9a4d48dba6b3d1dd4ac4abec
type: Opaque
stringData:
  username: svmAdmin
  password: fsqe2020
