apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: ontap-test-backend
  namespace: kube-system
spec:
  version: 1
  backendName: ontap-test
  storageDriverName: ontap-san
  managementLIF: 192.168.10.29
  dataLIF: 192.168.10.30
  svm: b5f26a3b9a4d48dba6b3d1dd4ac4abec
  credentials:
    name: tbc-user-pass
  sanType: nvme