---
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: local
  namespace: garden-local
  annotations:
    shoot.gardener.cloud/infrastructure-cleanup-wait-period-seconds: "0"
    shoot.gardener.cloud/cloud-config-execution-max-delay-seconds: "0"
    cluster.metal-stack.io/project: b5f26a3b-9a4d-48db-a6b3-d1dd4ac4abec
spec:
  seedName: local
  cloudProfileName: local
  secretBindingName: local # dummy, doesn't contain any credentials
  region: local
  extensions:
  - type: ontap
    providerConfig:
      apiVersion: ontap.metal.extensions.gardener.cloud/v1alpha1
      kind: TridentConfig
      svmIpaddresses:
        managementLif: "192.168.0.1" 
        dataLif: "192.168.0.2"   
  networking:
    type: calico
    nodes: 10.10.0.0/16
  provider:
    type: local
    workers:
    - name: local
      machine:
        type: local
      cri:
        name: containerd
      minimum: 1
      maximum: 1 # currently, only single-node clusters are supported
      maxSurge: 1
      maxUnavailable: 0
  kubernetes:
    kubelet:
      seccompDefault: true
      serializeImagePulls: false
      registryPullQPS: 10
      registryBurst: 20
      protectKernelDefaults: true
      streamingConnectionIdleTimeout: 5m
