apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: ontap-${PROJECT_ID}-backend
  namespace: kube-system
spec:
  version: 1
  backendName: ontap-${PROJECT_ID}
  storageDriverName: ontap-san
  sanType: nvme
  managementLIF: ontap-${PROJECT_ID}-mgmt-svc.kube-system.svc.cluster.local
  dataLIF: ontap-${PROJECT_ID}-data-svc.kube-system.svc.cluster.local
  svm: ${PROJECT_ID}
  credentials:
    name: ontap-svm-${PROJECT_ID}-credentials