apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: ontap-${PROJECT_ID}-backend
  namespace: kube-system
spec:
  version: 1
  backendName: ontap-${PROJECT_ID}
  storageDriverName: ontap-san
  sanType: nvme
  managementLIF: ontap-api
  credentials:
    name: ontap-svm-${PROJECT_ID}-credentials