apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trident-operator-rancher
  labels:
    app: operator.trident.netapp.io
subjects:
  - kind: ServiceAccount
    name: trident-operator
    namespace: trident
roleRef:
  kind: ClusterRole
  name: trident-operator-rancher
  apiGroup: rbac.authorization.k8s.io 