//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
2025 Copyright metal-stack Authors.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SvmIpaddresses) DeepCopyInto(out *SvmIpaddresses) {
	*out = *in
	if in.DataLifs != nil {
		in, out := &in.DataLifs, &out.DataLifs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SvmIpaddresses.
func (in *SvmIpaddresses) DeepCopy() *SvmIpaddresses {
	if in == nil {
		return nil
	}
	out := new(SvmIpaddresses)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TridentConfig) DeepCopyInto(out *TridentConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.SvmIpaddresses.DeepCopyInto(&out.SvmIpaddresses)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TridentConfig.
func (in *TridentConfig) DeepCopy() *TridentConfig {
	if in == nil {
		return nil
	}
	out := new(TridentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TridentConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
