image:
  repository: ghcr.io/metal-stack/gardener-extension-ontap
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1
resources: {}

controllers:
  concurrentSyncs: 5
  healthcheck:
    concurrentSyncs: 5
  heartbeat:
    renewIntervalSeconds: 30
  ignoreOperationAnnotation: false

disableControllers: []
disableWebhooks: []

webhookConfig:
  serverPort: "{{ index .Values.usablePorts 0 }}"

# imageVectorOverwrite: |
#   images:
#   - name: pause-container
#     sourceRepository: github.com/kubernetes/kubernetes/blob/master/build/pause/Dockerfile
#     repository: gcr.io/google_containers/pause-amd64
#     tag: "3.0"
#     version: 1.11.x
#   - name: pause-container
#     sourceRepository: github.com/kubernetes/kubernetes/blob/master/build/pause/Dockerfile
#     repository: gcr.io/google_containers/pause-amd64
#     tag: "3.1"
#     version: ">= 1.12"
#   ...

config:
  clientConnection:
    acceptContentTypes: application/json
    contentType: application/json
    qps: 100
    burst: 130
  clusters: 
  - name: cluster-a
    ipaddress: 192.168.10.11
    username: admin 
    password: fsqe2020


gardener:
  version: ""

usablePorts:
- 443  # webhook server
