apiVersion: v1
kind: Endpoints
metadata:
  name: ontap-${PROJECT_ID}-data-svc
  namespace: kube-system
  labels:
    app.kubernetes.io/part-of: gardener-extension-ontap
    app.kubernetes.io/managed-by: gardener
subsets:
  - addresses:
    - ip: ${DATA_LIF_IP}
    ports:
    - port: 4420
      name: https 