apiVersion: v1
kind: Service
metadata:
  name: ontap-${PROJECT_ID}-data-svc
  namespace: kube-system
  labels:
    app.kubernetes.io/part-of: gardener-extension-ontap
    app.kubernetes.io/managed-by: gardener
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https 
    port: 4420
    protocol: TCP
    targetPort: 4420 
  type: ClusterIP