apiVersion: v1
kind: Endpoints
metadata:
  name: ontap-${PROJECT_ID}-mgmt-svc 
  namespace: kube-system
  labels:
    app.kubernetes.io/part-of: gardener-extension-ontap
    app.kubernetes.io/managed-by: gardener
subsets:
- addresses:
  - ip: ${MANAGEMENT_LIF_IP}
  ports:
  - name: https 
    port: 443
    protocol: TCP 